version: "3.9"

services:
  db:
    image: mariadb:10.11
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wp
      MARIADB_PASSWORD: wp
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    volumes:
      # Live-edit plugins without rebuilding
      - ./wordpress-content/plugins:/var/www/html/wp-content/plugins
      # Allow the plugin to scan pages in the repo
      - ./src:/var/www/html/src:ro
    restart: unless-stopped

volumes:
  db_data: