name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the app
      - name: Build the app
        run: npm run build

      # Step 5: Tar the build locally
      - name: Archive dist directory
        run: tar -czf dist.tar.gz dist

      # Step 6: Upload using SCP
      - name: Upload dist.tar.gz
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist.tar.gz"
          target: ${{ secrets.SSH_TARGET_DIR }}
          strip_components: 0
          debug: true

      # Step 7: Extract on the server
      - name: Extract dist on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_TARGET_DIR }}
            tar --no-same-permissions --no-same-owner -xzf dist.tar.gz --strip-components=1
            rm dist.tar.gz